FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
COPY web/StockChatter.Web /src/web
COPY shared /shared
WORKDIR /src/web
RUN dotnet restore
RUN dotnet build -c Release -o /app/build --no-restore

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish --no-restore

FROM nginx:alpine as final
WORKDIR /usr/local/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY --from=publish /src/web/nginx.conf /etc/nginx/nginx.conf
