services:
  queue:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: StockChatter.Broker

  database:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=str0ngPwd!
    container_name: StockChatter.Database

  api:
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./StockChatter.API/Dockerfile
    image: stock-chatter-api:dev
    ports:
      - "5002:80"
      # - "5003:443" // Not possible now, needs certificates.
    container_name: StockChatter.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  bot:
    depends_on:
      - queue
    build:
      context: .
      dockerfile: ./StockChatter.Bot/Dockerfile
    image: stock-chatter-bot:dev
    container_name: StockChatter.Bot
    environment:
      - QUEUE_HOST_NAME=host.docker.internal
  
  app:
    build:
      context: .
      dockerfile: ./StockChatter/Dockerfile
    image: stock-chatter-app:dev
    ports:
      - "5000:80"
    container_name: StockChatter.App